CC := g++
CFLAG := -g 
TARGET:= context_ex
SRC:= context_main.cpp

all:$(TARGET)
	@echo "context switch model done..."

$(TARGET):$(SRC)
	$(CC) $(CFLAG) $(SRC) -o $(TARGET)

	
clean:
	rm -f $(TARGET)
